version: "3"

services:
  frontend:
    container_name: tempfiles-frontend
    image: ananjaemin/tempfiles-frontend:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./compose_data/frontend:/usr/share/nginx/html
    environment:
      - REACT_APP_BACKEND_BASEURL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - tempfiles-network

  backend:
    container_name: tempfiles-backend
    image: minpeter/tempfiles-backend:latest
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./compose_data/backend:/app/tmp
    environment:
      - BACKEND_BASE_URL=db:5432
      - BACKEND_PORT=5000
      - JWT_SECRET=simplesecret
      - DB_HOST=tempfiles-db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
    depends_on:
      - db
    networks:
      - tempfiles-network

  db:
    container_name: tempfiles-db
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./compose_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    networks:
      - tempfiles-network

networks:
  tempfiles-network:
