version: "3"

services:
  frontend:
    container_name: tempfiles-frontend
    image: ananjaemin/tempfiles-frontend:latest
    restart: always
    volumes:
      - ./compose_data/frontend:/usr/share/nginx/html
    depends_on:
      - backend
    labels:
      - traefik.http.routers.tmp-frontend.rule=Host(`tempfiles.ml`)
    networks:
      - traefik_default

  backend:
    container_name: tempfiles-backend
    image: minpeter/tempfiles-backend:latest
    restart: always
    volumes:
      - ./compose_data/backend:/app/tmp
    environment:
      - BACKEND_BASEURL=https://api.tempfiles.ml
      - BACKEND_PORT=5000
      - JWT_SECRET=simplesecret
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
    depends_on:
      - db
    labels:
      - traefik.http.routers.tmp-backend.rule=Host(`api.tempfiles.ml`)
      - traefik.http.services.tmp-backend.loadbalancer.server.port=5000
    networks:
      - traefik_default

  db:
    container_name: tempfiles-db
    image: postgres:latest
    restart: always
    volumes:
      - ./compose_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    networks:
      - traefik_default

networks:
  traefik_default:
    driver: bridge
    external: true
    internal: true
