 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tempfiles-ingress
spec:
  tls:
    - hosts:
        - tmp.k3s.minpeter.xyz
        - tmp-api.k3s.minpeter.xyz
      secretName: tempfiles-tls

  rules:
    - host: tmp.k3s.minpeter.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tempfiles-frontend-svc
                port:
                  number: 80
    - host: tmp-api.k3s.minpeter.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tempfiles-backend-svc
                port:
                  number: 5000
