apiVersion: v1
kind: ConfigMap

metadata:
  name: tempfiles-backend-config

data:
  BACKEND_BASEURL: https://tfb.minpeter.cf
  BACKEND_PORT: 5000
  JWT_SECRET: simplesecret@@

  DB_HOST: localhost
  DB_PORT: 5432
  DB_NAME: tempfilesdb
  DB_USER: admin
  DB_PASSWORD: simplesecret@@

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempfiles-backend-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tf-backpod
  template:
    metadata:
      name: tempfiles-backend-pod
      labels:
        app: tf-backpod
    spec:
      containers:
        - name: tempfiles-backend-container
          image: minpeter/tempfiles-backend
          envFrom:
            - configMapRef:
                name: tempfiles-backend-config
          ports:
            - containerPort: 5000
              name: tf-backend-port

---
apiVersion: v1
kind: Service
metadata:
  name: tempfiles-backend-svc
spec:
  ports:
    - name: tf-backend-svc-port
      port: 80
      targetPort: tf-backend-port
  selector:
    app: tf-backpod
  type: ClusterIP
